name: niaje
description: Voice assistant app powered by OpenAPI

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.4+4

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.6.2
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  logger: ^1.1.0
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
